### ISSUE TITLE
How to determine the default return type

### ISSUE THREAD

**Issue by rmohr** [emicklei/go-restful-openapi#10]
Currently 200 is always considered to be the default return value. That is obviously not always correct.

Guessing the default return code is hard. It depends on a combination of the fact if   body is returned, on the http method and of the specified .Responses(). To avoid including a lot of magical detection code, I would just add a `#DefaultReturns(code int, message string, model interface{})` method. As a fallback, when only one 2xx return is specified, this one is choosen.

@emicklei @wsong what do you think?

**Comment by rmohr** [comment]
Actually, I went through the spec here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object.

It looks like our understanding in the code is currently wrong. This basically allows setting the return type for anything else then specified. With that in mind I would definitely vote for having a `DefaultReturns` method and no detection at all.

**Comment by emicklei** [comment]
A DefaultReturns would be part of go-restful pkg , assuming that is what you mean.

Personally, I would not use this feature as it suggests that any other unspecified HTTP status code will return that model. That is simply not possible ; any http middleware could decide to answer differently.

Do you need this feature?

**Comment by rmohr** [comment]
It is less about that I need it. It is more about the current detection mechanism. I would at least remove that part which sets the default response to the return body of the 200 status code. I think this is not what was intended by the spec for this field.

Regarding to the DefaultReturns property, for instance kubernetes always returns a special `StatusError` when a not 2xx return code is sent back. It seems like it is there exactly for cases like this where you have the full control over your endpoint.

**Comment by emicklei** [comment]
ok, then let's add it so developers have a choice.
