### ISSUE TITLE
`time.Time` has no reference value

### ISSUE THREAD

**Issue by magiceses** [emicklei/go-restful-openapi#120]
When i use v2.9.2 , the `time.Time` is formated to `"$ref": "#/definitions/time.Time"`
<img width="652" alt="image" src="https://github.com/emicklei/go-restful-openapi/assets/50326171/d700696c-38e3-4c2c-b213-ba8ce1cd341c">

**Comment by emicklei** [comment]
thank you for reporting this. I will investigate

**Comment by emicklei** [comment]
included in `v2.10.2`
