### ISSUE TITLE
Json reference error when return type is pointer

### ISSUE THREAD

**Issue by ddysher** [emicklei/go-restful-openapi#13]
When using go-restful-openapi to generate swagger 2.0, we get the following json (truncated)

``` json
    "responses": {
      "200": {
       "description": "Success and respond with a array of space names",
       "schema": {
        "$ref": "#/definitions/%2Amodels.ListResponse"
       }
      },
      "default": {
       "description": "Success and respond with a array of space names",
       "schema": {
        "$ref": "#/definitions/%2Amodels.ListResponse"
       }
      }
```

`$ref` is invalid due to `%2A`, which stands for `*`.  Due to returning type being a pointer, the library incorrectly use *models.ListResponse as type name.

After a brief scan through the library, it seems I can just use `ModelTypeNameHandler` to bypass the problem; however, while building response, config is not injected into `definitionBuilder` so this workaround is not possible.

``` go
func buildResponse(e restful.ResponseError) (r spec.Response) {
	r.Description = e.Message
	if e.Model != nil {
		st := reflect.TypeOf(e.Model)
		modelName := definitionBuilder{}.keyFrom(st)
		r.Schema = new(spec.Schema)
		r.Schema.Ref = spec.MustCreateRef("#/definitions/" + modelName)
	}
	return r
}
```

So right now there are two to supply config to buildPaths, which calls buildResponse, and make ``ModelTypeNameHandler` work;
to deal with pointer type correctly in build responseapproaches off my head:
- to supply config to `buildPaths`, which calls `buildResponse`, and make ``ModelTypeNameHandler` work;
- to deal with pointer type correctly in `buildResponse`

Not sure if I catch the whole picture, feedback welcome :). I can put a PR if any fix is desirable.

**Comment by emicklei** [comment]
thank you analysing this problem. Work is still in progress so any help is appreciated.

- I think the ref should use the non-pointer type name.
- propagating the config must be fixed indeed.

Yes, please submit a PR.

**Comment by ddysher** [comment]
Thanks for confirming, will take a look ASAP.

Just to make sure I understand this comment; are u suggesting that the library should work as is, i.e. do not take special consideration for pointer type; it is caller's responsibility to not use pointer type?
> I think the ref should use the non-pointer type name.

**Comment by emicklei** [comment]
I meant it like a "normalization" step ; take the value type version if the sample is a pointer type.
