### ISSUE TITLE
Definition builder fails with custom types

### ISSUE THREAD

**Issue by vanbroup** [emicklei/go-restful-openapi#17]
We found that the definition builder is failing with custom types.

For example:
```
type Status int

const (
	UnknownStatus Status = iota
	FirstStatus 
	SecondStatus 
	ThirdStatus
)

func (s *Status) String() string {
	switch *s {
	case FirstStatus:
		return "First"
	case SecondStatus :
		return "Second"
	case ThirdStatus:
		return "Third"
	default:
		return "Unknown"
	}
}
```
Would trigger the definition builder to create a definition of main.Status, but the definition itself will never be created. Where for documentation purpose it would be great if the definition Status would be created with the constant information for documentation information a simpler solution is to change [line 200](https://github.com/emicklei/go-restful-openapi/blob/master/definition_builder.go#L200) of the definition builder.

From:
`fieldTypeName := b.keyFrom(fieldType)`

To:
`fieldTypeName := fieldType.Kind().String()`

We did some tests and this looks to be working fine, but it might have some other unexpected results. Any other suggestions?

**Comment by emicklei** [comment]
i am working on a test for this and checking the openapi spec on how to support this

**Comment by emicklei** [comment]
don't see solution to making this work.

**Comment by tekkamanendless** [comment]
Any update on this?

I'd be perfectly willing to add more markup somewhere or define a custom type in `go-restful` if that were an option.

**Comment by vanbroup** [comment]
@emicklei where are you getting stuck?

I was thinking that we can use reflect to detect the `String()` implementation and return type string when available. Similar to how you handle some object-specific definitions such as time.Time.

**Comment by emicklei** [comment]
it's been a while since I looked into this. Maybe with todays experience, I can come up with a solution/workaround

**Comment by emicklei** [comment]
today, i hit the same problem with `type Attribute_DataType int32` . Need a fix too.

**Comment by skyhit** [comment]
@emicklei any solution for this?

**Comment by erraggy** [comment]
@emicklei I have seen the same behavior with any struct field defined as type `interface{}` as well.

So the following will produce a model definition with an empty type definition of `domain.Foo.label`:
```
package domain

type struct Foo {
    Label interface{} `json:"label"`
    Count int `json:"count"`
}
```
Results in these 2 model definitions:
```
{
  "definitions": {
    "domain.Foo": {
      "required": [
        "label",
        "count"
      ],
      "properties": {
        "label": {
          "$ref": "#/definitions/domain.Foo.label"
        },
        "count": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "domain.Foo.label": {}
  }
}
```

**Comment by emicklei** [comment]
i am thinking about adding a field tag for this but it might only solve it for non-struct typed values.

**Comment by emicklei** [comment]
another idea is to test the actual type for implementing a certain interface that can tell the package what the actual openapi type should be. Something along the lines of:

```
type Attribute_DataType int32

func (t Attribute_DataType) SomeExtensionThatExistsForOpenAPI() { ... } 
```

I need to experiment with these ideas and have unit tests.

**Comment by erraggy** [comment]
I think the interface would be best (at least for our case), because the type is not known until runtime, so a type tag would not work here. In my example above for instance, the `Label` could be a string or some kind of number. 

If there was a method to implement that would satisfy what OpenAPI needs to know, what would it need to provide?

**Comment by emicklei** [comment]
@erraggy if the Label can be anything, what would the OpenAPI model be?  I guess type will be "object"

**Comment by emicklei** [comment]
the custom types problem, as stated by the OP, is solved by @nullbus . See v2.1.0
