### ISSUE TITLE
Slice parameters in body not exported correctly

### ISSUE THREAD

**Issue by benoitmasson** [emicklei/go-restful-openapi#18]
If I have a route which `Reads()` a slice, e.g., `Reads([]my.Object)`, in the `apidocs.json` it exported as:
```json
"parameters": [
  {
    "type": "[]my.Object",
    "default": "",
    "name": "body",
    "in": "body",
    "required": true,
    "schema": {
      "$ref": "#/definitions/%5B%5Dmy.Object"
    }
  }
]
```
while it should be:
```json
"parameters": [
  {
    "type": "[]my.Object",
    "default": "",
    "name": "body",
    "in": "body",
    "required": true,
    "schema": {
      "type": "array",
        "items": {
          "$ref": "#/definitions/my.Object"
        }
     }
  }
]
```
(i.e., an array type where items are a reference to the contained object)

**Comment by benoitmasson** [comment]
Oh, and I forgot but it also adds the following to the definitions:
```json
"definitions": {
  "||my.Object": {
    "id": "||my.Object"
   }
}
```
This should not be there, instead we should make sure that `my.Object` is defined (and add it if it is not)

**Comment by vbondarev** [comment]
Hello.
I have the same problem. When I use a simple object that is ok, but when I try to use an array of objects or pointer to an objects that is wrong.

For example:

`ws.Route(
		ws.PUT("/{lesson-id}/states").To(r.handler.RestfulUpdateActivityStates).
			Doc("Update the all activity states by the lesson uuid").
			Param(ws.PathParameter("lesson-id", "Identifier of the lesson").DataType("string")).
			Metadata(restfulspec.KeyOpenAPITags, tags).
			Reads([]models.ActivityState{}).
			Returns(http.StatusOK, http.StatusText(http.StatusOK), nil).
			Returns(http.StatusNotFound, http.StatusText(http.StatusNotFound), nil).
			Returns(http.StatusInternalServerError, http.StatusText(http.StatusInternalServerError), nil))`

In the output I get the mistake:
` Resolver error at paths./activity/{lesson-id}/states.put.parameters.1.schema.$ref
 Could not resolve reference because of: Could not resolve pointer: /definitions/%5B%5Dmodels.ActivityState does not exist in document`

If I change `Reads([]models.ActivityState{})` to `Reads(models.ActivityState{})` it works.

**Comment by emicklei** [comment]
need to write a test for this, and fix it

**Comment by emicklei** [comment]
recently there were quite some contributions to this package, please update and retry

**Comment by benoitmasson** [comment]
The problem remains with the latest commits. The following code:
```go
type Item struct{
	…
}
…
ws.Route(ws.POST("/items").To(i.addItems).
	// docs
	Metadata(openapi.KeyOpenAPITags, []string{"items"}).
	Operation("addItems").
	Reads([]Item{}).
	Writes([]Item{}))
```
leads to the following json:
```json
  "paths": {
    "/items": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "items"
        ],
        "operationId": "addItems",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/%5B%5Dresources.Item"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
```
As you can see, the body `parameter` is still not an array.

As for the definitions however, `||resources.Item` is not defined anymore and `resources.Item` is, which is a good thing

**Comment by emicklei** [comment]
hmm, why is there a ```%5B%5D``` in front of resources.Item ?

**Comment by benoitmasson** [comment]
It's always been there (see my initial comment).

It's the escaping of `[]`: I guess somewhere some package (`reflect`?) is telling that `[]Item{}` has type `"[]resources.Item"`, which is in turn escaped by the `json` package…

**Comment by emicklei** [comment]
see #33

**Comment by benoitmasson** [comment]
In fact, the problem remains **only** in the `"parameters"` object. `"responses"` are OK, as pointed out in #33.

Here is a complete, minimal example which fails:
```golang
package main

import (
	"log"
	"net/http"

	restful "github.com/emicklei/go-restful"
	openapi "github.com/emicklei/go-restful-openapi"
)

type Item struct {
	ID   int
	Name string
}

func main() {
	// initialize minimal items WS
	ws := new(restful.WebService)
	ws.Route(ws.POST("/items").To(addItems).
		// docs
		Metadata(openapi.KeyOpenAPITags, []string{"items"}).
		Operation("addItems").
		Reads([]Item{}).
		Writes([]Item{}). // not taken into account, only Returns() generates the "responses" object
		Returns(http.StatusOK, "created items are returned", []Item{}))

	// create container and add WS and apidocs.json
	wsContainer := restful.NewContainer()
	wsContainer.Add(ws)
	config := openapi.Config{
		WebServices: wsContainer.RegisteredWebServices(),
		APIPath:     "/apidocs.json",
	}
	wsContainer.Add(openapi.NewOpenAPIService(config))

	// run HTTP server
	host := "localhost:8888"
	http.Handle("/", wsContainer)
	log.Printf("Running REST server on http://%s", host)
	log.Fatal(http.ListenAndServe(host, nil))
}

func addItems(req *restful.Request, resp *restful.Response) {
	resp.WriteErrorString(http.StatusNotImplemented, "Not implemented")
}
```

This gives:
```sh
curl localhost:8888/apidocs.json
```
```js
{
  "swagger": "2.0",
  "paths": {
    "/items": {
      "post": {
        "tags": [
          "items"
        ],
        "operationId": "addItems",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/%5B%5Dmain.Item"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "created items are returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/main.Item"
              }
            }
          },
          "default": {
            "description": "created items are returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/main.Item"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "main.Item": {
      "required": [
        "ID",
        "Name"
      ],
      "properties": {
        "ID": {
          "type": "integer",
          "format": "int32"
        },
        "Name": {
          "type": "string"
        }
      }
    }
  }
}
```

=> `"responses"` and `"definitions"` are OK, not `"parameters"`

**Comment by emicklei** [comment]
thank you for investigating this and providing an example

**Comment by CrazyBBer** [comment]
issue still ,when read array from request ,it will build out a wrong path,such as:
```
Reads([]Object{}).
```
~~~
  "schema": {
              "$ref": "#/definitions/%5B%Object"
            }

~~~
detail as above

**Comment by emicklei** [comment]
can we close this?

**Comment by CrazyBBer** [comment]
> can we close this?

i think so.

**Comment by benoitmasson** [comment]
looks good, thanks a lot!
