### ISSUE TITLE
MapModelTypeNameFunc has incomplete behavior

### ISSUE THREAD

**Issue by benoitmasson** [emicklei/go-restful-openapi#19]
When set, the [`MapModelTypeNameFunc`](https://godoc.org/github.com/emicklei/go-restful-openapi#MapModelTypeNameFunc) renames models in the `"definitions"` of the `apidocs.json` file, but does not rename models in the `"paths"` section.

In particular, `"$ref"`'s contained in `"parameters"` or `"responses"` schemas remain unchanged. For example, if I choose to rename `my.Object` to `MyObject`, I get the following in `apidocs.json`:
```js
// "paths":
  "parameters": [
    {
      "type": "my.Object",
      "default": "",
      "name": "body",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/my.Object"
      }
    }
  ],
  "responses": {
    "200": {
      "schema": {
        "$ref": "#/definitions/my.Object"
      }
    }
  }

// "definitions":
{
  "MyObject": {
    "id": "MyObject",
    "properties": {
     "uuid": {
      "type": "string"
     }
  }
}
```
Of course, any spec reader will fail when trying to match `my.Object` in the parameters or response…

**Comment by emicklei** [comment]
this is indeed unintended behavior. I have to think about a solution to this. Any suggestions?

**Comment by emicklei** [comment]
is stil feature still on your need-to-have list?

**Comment by benoitmasson** [comment]
Currently I'm using a workaround to solve the issue (using the `PostBuildSwaggerObjectHandler` handler attribute, to fix the final structure).

It seems to work but it is a dirty hack, so yes I could use a fix, that would be far more reliable.

However, I don't know if you have plans to integrate OpenAPI v3 (https://github.com/OAI/OpenAPI-Specification) into go-restful, but if so, don't waste time on fixing this. I'd be very happy to migrate to OAS3 as soon as it becomes available!

Thanks

**Comment by emicklei** [comment]
@benoitmasson i have not looked into the changes that v3 introduces, do you think we can make this repository compatible to both?

**Comment by austince** [comment]
Hi there 👋🏼 sorry to drudge up an old issue, but want to check before creating a new one: Is OpenAPI 3.x supported, or is this project only going to target 2.x?

**Comment by emicklei** [comment]
@austince good question. TBH I have not yet looked at the differences for a while and apparently there is not much interest.  We could start a new branch v3 with a copy of the latest v2 and start doing renames to meet the spec.  Would you like contribute to that?

**Comment by austince** [comment]
Hey @emicklei thanks for the quick reply. It looks like the go community as a whole has been slow to adopt the 3.x spec (k8s just recently merged a KEP around it https://github.com/kubernetes/enhancements/issues/2896). I'm not sure I'm the right person to contribute, unfortunately – I'm still evaluating tools and think I'm looking for more standalone generation vs. building at runtime. But if that changes, happy to see what I can do to help!
