### ISSUE TITLE
Use OAI3 specification instead of OAI2

### ISSUE THREAD

**Issue by OmidHekayati** [emicklei/go-restful-openapi#2]
OAI2 is almost at EOL (End-of-life) and I suggest to work on oai3. they almost ready to publish preview it in less than a month and all document can find here:
https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md

**Comment by emicklei** [comment]
I see you point. However, currently there does not seem to be a Go implementation of the spec. And what is the status of the UI and other tooling?
We could start with 2 in the repository  go-restful-openapi2  and later duplicate+modify into  go-restful-openapi3

**Comment by OmidHekayati** [comment]
I think it isn't good idea to include version in repo name. Git is a version control and version number can be set in release cycle.
You are correct and it seems there is no go spec yet. for oai2 we can use this:
https://github.com/go-openapi/spec

**Comment by dkiser** [comment]
I see this popped up not too long ago: https://github.com/go-openapi/spec3.
