### ISSUE TITLE
All struct fields are marked as required

### ISSUE THREAD

**Issue by benoitmasson** [emicklei/go-restful-openapi#20]
When a struct is used as input parameter in the body (with `Reads(MyStruct)`), all struct fields are automatically set as `"required"` in the `apidocs.json`.

It would be great to be able to customize this via tags, for example with a new `optional` tag:
```golang
type MyStruct struct {
  RequiredField int `description:"this is a required field"`
  OptionalField int `description:"this is an optional field" optional:"true"`
}
```
or as an option to the `description` tag:
```golang
type MyStruct struct {
  RequiredField int `description:"this is a required field"`
  OptionalField int `description:"this is an optional field,optional"`
}
```

**Comment by emicklei** [comment]
good idea.  is there a conventional approach here?  i favor the separate tag "optional"

**Comment by benoitmasson** [comment]
I don't really know… both seem reasonnably good solutions to me.

However, the separate tag is clearly better for parsing (how to handle complex descriptions with commas in the case of a simple option?), so I'd go for that too.

The risk is that it may interfere with other packages using an `optional` tag… if any. And the name is explicit enough so that I think this is not a big issue.

**Comment by emicklei** [comment]
back from my holidays, time to work on the open issues. Will use "optional" here.

**Comment by emicklei** [comment]
see https://github.com/emicklei/go-restful-openapi/commit/0d037b269a5b53b582789e25dee0d0a0614119e5
