### ISSUE TITLE
Json Reference Error when Response is Array of String

### ISSUE THREAD

**Issue by cliang57** [emicklei/go-restful-openapi#24]
My Get API returns an array of strings. I uses go-restful 2.0 and go-restful-openapi package.

The API works.
But my Swagger UI page shows error 'Could not resolve reference because of: Could not resolve pointer: /definitions/string does not exist in document'.

This is part of my apidocs.json
`
"responses": {
    "200": {
        "description": "OK",
        "schema": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/string"
            }
        }
    },
`

I think the problem may be go-restful-openapi does not check for primitive types when building the response description.

My suggestion would be modify 'build_path.go' to use 'isPrimitiveType()' and 'jsonSchemaType()' to check and map primitive type if necessary, just like you did in 'definition_builder.go'.

**Comment by cliang57** [comment]
I created a pull request. This patch fixed my problem. Hope go-restful-open api can adopt it or make similar updates.
https://github.com/emicklei/go-restful-openapi/pull/25

**Comment by emicklei** [comment]
thanks, I merged it just now
