### ISSUE TITLE
securityDefinitions spec

### ISSUE THREAD

**Issue by dkiser** [emicklei/go-restful-openapi#30]
Are there any examples of producing a `securityDefinitions` specification entry to support describing authentication?  Would this be a manual function now using an `enrichSwaggerObject` function?

**Comment by dkiser** [comment]
Did a bit of research and I guess you can do things like the following that seem to work pretty well.

```go
	swo.SecurityDefinitions = map[string]*spec.SecurityScheme{
		"jwt":   spec.APIKeyAuth("Authorization", "header"),
		"basic": spec.BasicAuth(),
	}

	swo.Security = []map[string][]string{
		{"jwt": {}},
	}
```

Too bad OAPI2.0 doesn't support the `Bearer` auth scheme 8-).

**Comment by emicklei** [comment]
yes, my first reaction would have been using the enrich function; that's why it was created.

**Comment by dkiser** [comment]
@emicklei whipped up an example here where `Metadata` on a `restful.Route` can be used to dynamically update the `*spec.Swagger` to map `Security` entries to `SecurityDefinition` entries for each route. 

If you think it's worth adding something like this to an existing or additional example service let me know.

https://gist.github.com/dkiser/267f5aee0164b69c9b5efd028c645aa5

**Comment by emicklei** [comment]
hi, thank you for putting this example together. Could you send me a PR for an additional example to add here?

**Comment by dkiser** [comment]
Sure, give me a few days here and i'll add one in the examples folder.
