### ISSUE TITLE
How to write/return array of strings?

### ISSUE THREAD

**Issue by objque** [emicklei/go-restful-openapi#33]
Hello, one of my controllers returns `[]string` 

```go
...
		Writes([]string{}).
		Returns(http.StatusOK, http.StatusText(http.StatusOK), []string{}))
```

And when I build and paste doc into editor.swagger I see errors

![2017-10-06 20 22 14](https://user-images.githubusercontent.com/7000585/31290162-1b5c50e8-aad4-11e7-8388-5de5803fcac6.png)

I haven't problems with custom types. Is it my fault or not?

**Comment by emicklei** [comment]
hi, thank you for reporting this. I will need to create a test for this and see what the spec acutally needs to be.

**Comment by emicklei** [comment]
in the examples folder, there is a user-resource.go file.

I added the following snippet for a quick view of the problem

```
	ws.Route(ws.GET("/names").To(u.findAllUsers).
		// docs
		Doc("get the names of all users").
		Metadata(restfulspec.KeyOpenAPITags, tags).
		Writes([]string{}).
		Returns(200, "OK", []string{}))
```
The response returned from http://localhost:8080/apidocs.json shows
```
        "summary": "get the names of all users",
        "operationId": "findAllUsers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "default": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
```

**Comment by emicklei** [comment]
so my example does not show this problem. Can you confirm?

**Comment by objque** [comment]
I'll check it tomorrow, promise you :)
