### ISSUE TITLE
go-restful-openapi can not work with swagger-ui 3.x

### ISSUE THREAD

**Issue by CrazyBBer** [emicklei/go-restful-openapi#34]
1、 pull a swagger-ui 3.x(the latest version) from dockerhub 
2、run a container from the pulled image.
3、go run the user-resource sample 
4、explorer the url： http://localhost:8080/apidocs.json  
5、failed

**Comment by emicklei** [comment]
i recall this issue from https://github.com/emicklei/go-restful-openapi/commit/1f0ce081cba8bb07e4f60f300ce22751e9b596fa . 
Assuming you are using the latest commit, I will repeat your experiment to verify it.

**Comment by CrazyBBer** [comment]
it looks like  the "Access-Control-Allow-Origin" issue .

error found in browser  as following  :
No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by CrazyBBer** [comment]
when post a create request from the swagger-ui page using the generated apidoc  , there is a followed issue: 
web console get a  error : Response to preflight request doesn't pass access control check  .
the post request could not reach the resource handler.

**Comment by CrazyBBer** [comment]
@emicklei 
problem solved.  
it could be solved by using  **CrossOriginResourceSharing**  filter 
you already gave a demo in example .
sorry  to take trouble for u.

**Comment by emicklei** [comment]
@CrazyBBer no problem, thank you for looking into this issue. Do we need to update the user-resource example accordingly?

**Comment by CrazyBBer** [comment]
@emicklei 
considering easily to user , it's better to update the user-resource  example, i think . if so:

**adding the following codes**
```
	// Add container filter to enable CORS
	cors := restful.CrossOriginResourceSharing{
		ExposeHeaders:  []string{"X-My-Header"},
		AllowedHeaders: []string{"Content-Type", "Accept"},
		AllowedMethods: []string{"GET", "POST"},
		CookiesAllowed: false,
		Container:      wsContainer}
	wsContainer.Filter(cors.Filter)
```
code from link : https://github.com/emicklei/go-restful/blob/master/examples/restful-CORS-filter.go
