### ISSUE TITLE
"Notes" not used

### ISSUE THREAD

**Issue by vikstrous** [emicklei/go-restful-openapi#35]
Operation.Description should be set to the Notes from the route. Instead, the Doc field is used and the first line of the Doc field is used as the "Summary". The notes should be what's used in the description to stay consistent with the swagger 1.2 implementation. PR incoming...

**Comment by emicklei** [comment]
without looking at the impl yet, will this "break" existing use of the package?

**Comment by emicklei** [comment]
did you consider adding a new method in Route instead?

**Comment by vikstrous** [comment]
There are already two methods: Doc and Info. Info is the description in swagger 1.2 but it's not used in swagger 2 (this repo). In swagger 2 Doc is used as the description. My proposal is so make the behaviour the same between the two and use Info as the description.

**Comment by emicklei** [comment]
can only agree to that 👍
