### ISSUE TITLE
WebServicesURL defined but not used?

### ISSUE THREAD

**Issue by spellgen** [emicklei/go-restful-openapi#39]
Similar to the swagger (1.2) api for go-restful, the openapi version defines `WebServicesURL` in the `Config` struct, but it appears not to be used or have any effect on how the defined endpoints are called.
I strip the service-part of the URL that defines my endpoints, so without having this variable respected "Try it out!" calls are made to: "https://example.com/endpoint" instead of "https://example.com/service/endpoint".

**Comment by emicklei** [comment]
you are correct, this field is a left-over from an old state of the package when it was also providing the feature to serve the swagger docs and artifacts.  I think it can be removed safely

**Comment by emicklei** [comment]
i marked the field as deprecated
