### ISSUE TITLE
How to serve the Swagger UI

### ISSUE THREAD

**Issue by the42** [emicklei/go-restful-openapi#4]
The old repository contained configuration parameters to serve the Swagger  UI as eg.

 SwaggerPath:     "/apidocs/",
    SwaggerFilePath: "/Users/emicklei/Projects/swagger-ui/dist"}

is this planned to be added later or even already supported with go-restful-openapi?

If not, does that mean that serving the swagger UI (which is not an issue) is left to the user?

Thank you

**Comment by emicklei** [comment]
@the42 , yes, serving the UI is left to the user.  Recent projects here have shown that developers use different strategies here (different port, TLS, serving statics via go-bindata,...) so I decided to not include it.

I will update the example accordingly.
