### ISSUE TITLE
support additionalProperties

### ISSUE THREAD

**Issue by Jack47** [emicklei/go-restful-openapi#40]
Currently go-restful-openapi don't support [additionalProperties](https://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties). It's useful for scenearios like below.

```
type GroupInfo struct {
  count int
  members  map[string]MemberInfo
}
type MemberInfo struct {
  name string
  endpoint string
}
```

We can use additionalProperties to generate schema for `members`:
```
members: {
  "type": "object",
  "patternProperties": {
    "^[a-zA-Z]+$": {
       "type": "object",
       "properties": {
          "name": {"type": "string"},
          "endpoint": {"type": "string"}
       },
       "additionalProperties": true
    }
  }
}
```
Do you have some suggestions on this?

**Comment by emicklei** [comment]
did you try implementing a PostBuildSwaggerObjectHandler function? It takes a Swagger object of the complete configuration. You could use that now to change the Model.

An alternative could be having such a hook (PostBuild) on the type itself.
For instance, let say the GroupInfo was extended with

```
func (g GroupInfo) PostBuildOpenAPISchema(*spec.Schema) {}
```

With this you could modify it directly.

**Comment by Jack47** [comment]
Thanks for response. Use `PostBuildOpenAPISchema()` can solve this problem, but IMHO it's not very straight forward. It would be better to let go-restful-openapi recognize `members map[string]MemberInfo` and generate complete swagger doc for it.

Currently go-restful-openapi can only generate swagger doc:
```
members: {
  "type": "object"
}
```
The above  doc is incomplete because user don't know what's in the members. go-restful-openapi don't leverage the definition of `MemberInfo`. I'm wondering whether we can support `patternProperties` in struct tag like this:
```
type GroupInfo struct {
  count int
  members  map[string]MemberInfo `patternProperties:"^[a-zA-Z]+$"`
}
```

Then we can generate swagger doc like this:
```
members: {
  "type": "object",
  "patternProperties": {
    "^[a-zA-Z]+$": {
       "type": "object",
       "properties": {
          "name": {"type": "string"},
          "endpoint": {"type": "string"}
       },
       "additionalProperties": true
    }
  }
}
```
Just my quick thoughts, may be we can reference from other language implementations. How does Java convert `members map<string, MemberInfo>` into swagger doc?

**Comment by emicklei** [comment]
According to https://swagger.io/docs/specification/data-models/dictionaries/ also a $ref can be used.

**Comment by Jack47** [comment]
Sure, we can use inline schema or use $ref.

**Comment by tekkamanendless** [comment]
If the intent of this issue is to support maps of well-defined types, then #44 might do what you want.
