### ISSUE TITLE
Should we support lowerCamelCase with setting

### ISSUE THREAD

**Issue by slow-zhang** [emicklei/go-restful-openapi#80]
my project wants to unify the format of JSON key to lowerCamelCase (the project has some tag in lowerCamelCase). but by default non-JSON-tagged value will generate UpperCamelCase.

Can we add a config to change the default action?

----
btw, I have found a place to change it but not sure it's enough: (change `return field.Name` to `return  strings.ToLower(field.Name[:1]) + field.Name[1:]`)

![image](https://user-images.githubusercontent.com/24769636/141971228-cb5d7dfb-5fd9-4ae8-9722-b0da614246fb.png)

**Comment by SVilgelm** [comment]
you can do it by using json tag in your structures:
```go
type A {
    NyFieldA    `json:"myFieldA"`
}
```

Here is a good explanation about structure tags: https://www.digitalocean.com/community/tutorials/how-to-use-struct-tags-in-go

**Comment by slow-zhang** [comment]
yeah，it works. but in my project, there are lots of external structs, its hard to add tag for them

---Original---
From: "Sergey ***@***.***&gt;
Date: Fri, Nov 19, 2021 00:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [emicklei/go-restful-openapi] Should we support lowerCamelCase with setting (Issue #80)




 
you can do it by using json tag in your structures:
 type A {     NyFieldA    `json:"myFieldA"` }
 
Here is a good explanation about structure tags: https://www.digitalocean.com/community/tutorials/how-to-use-struct-tags-in-go

**Comment by emicklei** [comment]
@slow-zhang , one solution could be to introduce a JSONFieldNameHandler in Config which, if present, is called to do any transformation on the name

**Comment by emicklei** [comment]
@slow-zhang Do you want to work on a PR for this?

**Comment by slow-zhang** [comment]
***@***.***：377636000地址：浙江省杭州市西湖区浙江大学西溪校区

**Comment by slow-zhang** [comment]
this cool, i will work on it

**Comment by emicklei** [comment]
feature added. thx
